[2024-01-28T13:11:21.349+0100] {processor.py:161} INFO - Started process (PID=5448) to work on /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:11:21.350+0100] {processor.py:830} INFO - Processing file /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-28T13:11:21.351+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:11:21.350+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:11:21.355+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:11:21.355+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-28T13:11:21.356+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:11:21.356+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-28T13:11:21.356+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:11:21.369+0100] {processor.py:183} INFO - Processing /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-01-28T13:12:31.032+0100] {processor.py:161} INFO - Started process (PID=5617) to work on /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:12:31.033+0100] {processor.py:830} INFO - Processing file /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-28T13:12:31.034+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:12:31.034+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:12:31.039+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:12:31.038+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-28T13:12:31.039+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:12:31.039+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-28T13:12:31.039+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:12:31.050+0100] {processor.py:183} INFO - Processing /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-01-28T13:13:33.865+0100] {processor.py:161} INFO - Started process (PID=5756) to work on /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:13:33.866+0100] {processor.py:830} INFO - Processing file /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-28T13:13:33.867+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:13:33.867+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:13:33.871+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:13:33.870+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-28T13:13:33.871+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:13:33.871+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-28T13:13:33.871+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:13:33.891+0100] {processor.py:183} INFO - Processing /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-01-28T13:14:30.343+0100] {processor.py:161} INFO - Started process (PID=5874) to work on /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:14:30.346+0100] {processor.py:830} INFO - Processing file /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-01-28T13:14:30.347+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:14:30.347+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:14:30.353+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:14:30.351+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-01-28T13:14:30.353+0100] {logging_mixin.py:188} INFO - [2024-01-28T13:14:30.353+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-01-28T13:14:30.353+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-01-28T13:14:30.366+0100] {processor.py:183} INFO - Processing /home/hadoop/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
