[2024-01-28T15:55:36.811+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summoner_id_dag.fetch_summoner_ids manual__2024-01-28T14:55:33.083254+00:00 [queued]>
[2024-01-28T15:55:36.817+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summoner_id_dag.fetch_summoner_ids manual__2024-01-28T14:55:33.083254+00:00 [queued]>
[2024-01-28T15:55:36.817+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-28T15:55:36.832+0100] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): fetch_summoner_ids> on 2024-01-28 14:55:33.083254+00:00
[2024-01-28T15:55:36.836+0100] {standard_task_runner.py:60} INFO - Started process 17289 to run task
[2024-01-28T15:55:36.839+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'summoner_id_dag', 'fetch_summoner_ids', 'manual__2024-01-28T14:55:33.083254+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/summoner_id_dag.py', '--cfg-path', '/tmp/tmp3xbnms34']
[2024-01-28T15:55:36.844+0100] {standard_task_runner.py:88} INFO - Job 6: Subtask fetch_summoner_ids
[2024-01-28T15:55:36.875+0100] {task_command.py:423} INFO - Running <TaskInstance: summoner_id_dag.fetch_summoner_ids manual__2024-01-28T14:55:33.083254+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-28T15:55:36.932+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nekruzk@3il.fr' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='summoner_id_dag' AIRFLOW_CTX_TASK_ID='fetch_summoner_ids' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T14:55:33.083254+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-28T14:55:33.083254+00:00'
[2024-01-28T15:55:36.933+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-28T15:55:36.934+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/hadoop/Desktop/projectBD/scripts/fetch_summoner_ids.py ']
[2024-01-28T15:55:36.945+0100] {subprocess.py:86} INFO - Output:
[2024-01-28T15:55:48.534+0100] {subprocess.py:93} INFO - Successfully uploaded /home/hadoop/Desktop/projectBD/scripts/../summoner_details.json to /user/hadoop/lol/raw
[2024-01-28T15:55:48.565+0100] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-28T15:55:48.594+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=summoner_id_dag, task_id=fetch_summoner_ids, execution_date=20240128T145533, start_date=20240128T145536, end_date=20240128T145548
[2024-01-28T15:55:48.644+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-28T15:55:48.652+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
