[2024-01-29T01:01:06.272+0100] {taskinstance.py:1947} INFO - Dependencies not met for <TaskInstance: match_histories_dag.fetch_match_histories manual__2024-01-29T00:00:28.160078+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-01-29T01:01:06.277+0100] {local_task_job_runner.py:160} INFO - Task is not able to be run
