[2024-01-29T01:10:36.453+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-29T00:10:07.640614+00:00 [queued]>
[2024-01-29T01:10:36.465+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-29T00:10:07.640614+00:00 [queued]>
[2024-01-29T01:10:36.466+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-29T01:10:36.504+0100] {taskinstance.py:2192} INFO - Executing <Task(TriggerDagRunOperator): trigger_match_id_dag> on 2024-01-29 00:10:07.640614+00:00
[2024-01-29T01:10:36.511+0100] {standard_task_runner.py:60} INFO - Started process 21499 to run task
[2024-01-29T01:10:36.517+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'summoner_id_dag', 'trigger_match_id_dag', 'manual__2024-01-29T00:10:07.640614+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/summoner_id_dag.py', '--cfg-path', '/tmp/tmpo9oha23f']
[2024-01-29T01:10:36.521+0100] {standard_task_runner.py:88} INFO - Job 54: Subtask trigger_match_id_dag
[2024-01-29T01:10:36.583+0100] {task_command.py:423} INFO - Running <TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-29T00:10:07.640614+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-29T01:10:36.766+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='irachide1@gmail.com' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='summoner_id_dag' AIRFLOW_CTX_TASK_ID='trigger_match_id_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T00:10:07.640614+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T00:10:07.640614+00:00'
[2024-01-29T01:10:37.010+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=summoner_id_dag, task_id=trigger_match_id_dag, execution_date=20240129T001007, start_date=20240129T001036, end_date=20240129T001037
[2024-01-29T01:10:37.082+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-29T01:10:37.104+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
