[2024-01-29T01:03:02.680+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-29T00:02:46.685561+00:00 [queued]>
[2024-01-29T01:03:02.690+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-29T00:02:46.685561+00:00 [queued]>
[2024-01-29T01:03:02.690+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-29T01:03:02.721+0100] {taskinstance.py:2192} INFO - Executing <Task(TriggerDagRunOperator): trigger_match_id_dag> on 2024-01-29 00:02:46.685561+00:00
[2024-01-29T01:03:02.725+0100] {standard_task_runner.py:60} INFO - Started process 18740 to run task
[2024-01-29T01:03:02.729+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'summoner_id_dag', 'trigger_match_id_dag', 'manual__2024-01-29T00:02:46.685561+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/summoner_id_dag.py', '--cfg-path', '/tmp/tmp66b849bk']
[2024-01-29T01:03:02.731+0100] {standard_task_runner.py:88} INFO - Job 44: Subtask trigger_match_id_dag
[2024-01-29T01:03:02.795+0100] {task_command.py:423} INFO - Running <TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-29T00:02:46.685561+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-29T01:03:02.872+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='irachide1@gmail.com' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='summoner_id_dag' AIRFLOW_CTX_TASK_ID='trigger_match_id_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T00:02:46.685561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T00:02:46.685561+00:00'
[2024-01-29T01:03:03.056+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=summoner_id_dag, task_id=trigger_match_id_dag, execution_date=20240129T000246, start_date=20240129T000302, end_date=20240129T000303
[2024-01-29T01:03:03.126+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-29T01:03:03.144+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
