[2024-01-29T01:25:21.655+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: match_id_dag.trigger_match_histories_dag manual__2024-01-29T00:25:03.272330+00:00 [queued]>
[2024-01-29T01:25:21.659+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: match_id_dag.trigger_match_histories_dag manual__2024-01-29T00:25:03.272330+00:00 [queued]>
[2024-01-29T01:25:21.659+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-29T01:25:21.677+0100] {taskinstance.py:2192} INFO - Executing <Task(TriggerDagRunOperator): trigger_match_histories_dag> on 2024-01-29 00:25:03.272330+00:00
[2024-01-29T01:25:21.680+0100] {standard_task_runner.py:60} INFO - Started process 25318 to run task
[2024-01-29T01:25:21.683+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'match_id_dag', 'trigger_match_histories_dag', 'manual__2024-01-29T00:25:03.272330+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/match_id_dag.py', '--cfg-path', '/tmp/tmp5za_9d2s']
[2024-01-29T01:25:21.685+0100] {standard_task_runner.py:88} INFO - Job 61: Subtask trigger_match_histories_dag
[2024-01-29T01:25:21.714+0100] {task_command.py:423} INFO - Running <TaskInstance: match_id_dag.trigger_match_histories_dag manual__2024-01-29T00:25:03.272330+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-29T01:25:21.764+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='irachide1@gmail.com' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='match_id_dag' AIRFLOW_CTX_TASK_ID='trigger_match_histories_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T00:25:03.272330+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T00:25:03.272330+00:00'
[2024-01-29T01:25:21.807+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=match_id_dag, task_id=trigger_match_histories_dag, execution_date=20240129T002503, start_date=20240129T002521, end_date=20240129T002521
[2024-01-29T01:25:21.827+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-29T01:25:21.836+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
