[2024-01-29T00:56:28.901+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-28T23:56:11.337239+00:00 [queued]>
[2024-01-29T00:56:28.907+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-28T23:56:11.337239+00:00 [queued]>
[2024-01-29T00:56:28.908+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-29T00:56:28.934+0100] {taskinstance.py:2192} INFO - Executing <Task(TriggerDagRunOperator): trigger_match_id_dag> on 2024-01-28 23:56:11.337239+00:00
[2024-01-29T00:56:28.938+0100] {standard_task_runner.py:60} INFO - Started process 17048 to run task
[2024-01-29T00:56:28.942+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'summoner_id_dag', 'trigger_match_id_dag', 'manual__2024-01-28T23:56:11.337239+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/summoner_id_dag.py', '--cfg-path', '/tmp/tmpbcps_fpo']
[2024-01-29T00:56:28.944+0100] {standard_task_runner.py:88} INFO - Job 29: Subtask trigger_match_id_dag
[2024-01-29T00:56:28.978+0100] {task_command.py:423} INFO - Running <TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-28T23:56:11.337239+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-29T00:56:29.030+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='irachide1@gmail.com' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='summoner_id_dag' AIRFLOW_CTX_TASK_ID='trigger_match_id_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T23:56:11.337239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-28T23:56:11.337239+00:00'
[2024-01-29T00:56:29.131+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=summoner_id_dag, task_id=trigger_match_id_dag, execution_date=20240128T235611, start_date=20240128T235628, end_date=20240128T235629
[2024-01-29T00:56:29.186+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-29T00:56:29.194+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
