[2024-01-29T01:29:04.266+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-29T00:28:47.219036+00:00 [queued]>
[2024-01-29T01:29:04.270+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-29T00:28:47.219036+00:00 [queued]>
[2024-01-29T01:29:04.271+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-29T01:29:04.285+0100] {taskinstance.py:2192} INFO - Executing <Task(TriggerDagRunOperator): trigger_match_id_dag> on 2024-01-29 00:28:47.219036+00:00
[2024-01-29T01:29:04.289+0100] {standard_task_runner.py:60} INFO - Started process 27156 to run task
[2024-01-29T01:29:04.292+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'summoner_id_dag', 'trigger_match_id_dag', 'manual__2024-01-29T00:28:47.219036+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/summoner_id_dag.py', '--cfg-path', '/tmp/tmp8hgw6c2s']
[2024-01-29T01:29:04.294+0100] {standard_task_runner.py:88} INFO - Job 64: Subtask trigger_match_id_dag
[2024-01-29T01:29:04.326+0100] {task_command.py:423} INFO - Running <TaskInstance: summoner_id_dag.trigger_match_id_dag manual__2024-01-29T00:28:47.219036+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-29T01:29:04.381+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='irachide1@gmail.com' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='summoner_id_dag' AIRFLOW_CTX_TASK_ID='trigger_match_id_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T00:28:47.219036+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T00:28:47.219036+00:00'
[2024-01-29T01:29:04.493+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=summoner_id_dag, task_id=trigger_match_id_dag, execution_date=20240129T002847, start_date=20240129T002904, end_date=20240129T002904
[2024-01-29T01:29:04.528+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-29T01:29:04.536+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
